[build]
  builder = "nixpacks"
  buildCommand = "composer install --optimize-autoloader --no-interaction --no-scripts && npm install --legacy-peer-deps && npm run build && php artisan storage:link"

[deploy]
  startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
  healthcheckPath = "/"
  healthcheckTimeout = 100
  restartPolicyType = "on_failure"

[phases.setup]
  nixPkgs = ["nodejs", "npm"]

[[services]]
  name = "web"
  type = "web"
  plan = "free"
  envVars = []
  domains = []
  ports = [{port = 8000, type = "http"}]
