[build]
  builder = "nixpacks"
  buildCommand = "composer install --optimize-autoloader --no-interaction --no-scripts && npm install --legacy-peer-deps && npm run build && php artisan key:generate --force && php artisan storage:link && php artisan config:cache && php artisan route:cache && php artisan view:cache && chmod -R 775 storage bootstrap/cache"

[deploy]
  startCommand = "php artisan migrate --force && php artisan optimize && php artisan serve --host=0.0.0.0 --port=$PORT"
  healthcheckPath = "/up"
  healthcheckTimeout = 100
  restartPolicyType = "on_failure"

[phases.setup]
  nixPkgs = ["nodejs", "npm"]

[[services]]
  name = "web"
  type = "web"
  plan = "free"
  envVars = []
  domains = []
  ports = [{port = 8000, type = "http"}]
